-- ============================================================================
-- 30_load_reconciliation.sql
-- Refreshes RECONCILIATION.LOAD_SUMMARY: for every loaded bundle, compares
-- how many entries of each resourceType existed in RAW.BUNDLE_RAW against how
-- many rows actually landed in the matching FOUNDATION table.
--
-- Full refresh (truncate + reinsert) so RECONCILIATION.LOAD_SUMMARY always
-- reflects the current state of RAW + FOUNDATION -- run after 20_load_foundation.sql,
-- and again any time either layer changes. This is the table a Reconciliation
-- Agent queries to answer "did every message get fully split?" questions.
-- ============================================================================

USE DATABASE HEALTHCARE_INTELLIGENCE_DB;
USE SCHEMA RECONCILIATION;

TRUNCATE TABLE RECONCILIATION.LOAD_SUMMARY;

INSERT INTO RECONCILIATION.LOAD_SUMMARY
    (TRACKING_ID, SOURCE_FILE_NAME, RESOURCE_TYPE, RAW_ENTRY_COUNT, FOUNDATION_LOADED_COUNT, STATUS)
WITH RAW_COUNTS AS (
    -- Every resourceType present in RAW, per bundle -- includes types with no
    -- FOUNDATION table (e.g. Organization, Location, Practitioner) on purpose.
    SELECT
        b.TRACKING_ID,
        b.SOURCE_FILE_NAME,
        e.value:resource:resourceType::VARCHAR AS RESOURCE_TYPE,
        COUNT(*) AS RAW_ENTRY_COUNT
    FROM RAW.BUNDLE_RAW b,
         LATERAL FLATTEN(input => b.BUNDLE_JSON:entry) e
    GROUP BY b.TRACKING_ID, b.SOURCE_FILE_NAME, e.value:resource:resourceType::VARCHAR
),
FOUNDATION_COUNTS AS (
    SELECT 'Patient' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.PATIENT
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Encounter' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.ENCOUNTER
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Condition' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.CONDITION
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Observation' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.OBSERVATION
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Procedure' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.PROCEDURE
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Claim' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.CLAIM
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'ExplanationOfBenefit' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.EXPLANATION_OF_BENEFIT
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'DiagnosticReport' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.DIAGNOSTIC_REPORT
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'DocumentReference' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.DOCUMENT_REFERENCE
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Immunization' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.IMMUNIZATION
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'MedicationRequest' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.MEDICATION_REQUEST
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Medication' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.MEDICATION
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'MedicationAdministration' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.MEDICATION_ADMINISTRATION
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'CareTeam' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.CARE_TEAM
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'CarePlan' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.CARE_PLAN
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'SupplyDelivery' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.SUPPLY_DELIVERY
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Provenance' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.PROVENANCE
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'AllergyIntolerance' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.ALLERGY_INTOLERANCE
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'Device' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.DEVICE
    GROUP BY BUNDLE_TRACK_ID_REF
UNION ALL
    SELECT 'ImagingStudy' AS RESOURCE_TYPE, BUNDLE_TRACK_ID_REF AS TRACKING_ID, COUNT(*) AS FOUNDATION_LOADED_COUNT
    FROM FOUNDATION.IMAGING_STUDY
    GROUP BY BUNDLE_TRACK_ID_REF
)
SELECT
    r.TRACKING_ID,
    r.SOURCE_FILE_NAME,
    r.RESOURCE_TYPE,
    r.RAW_ENTRY_COUNT,
    COALESCE(f.FOUNDATION_LOADED_COUNT, 0) AS FOUNDATION_LOADED_COUNT,
    CASE
        WHEN r.RESOURCE_TYPE NOT IN (
        'Patient',
        'Encounter',
        'Condition',
        'Observation',
        'Procedure',
        'Claim',
        'ExplanationOfBenefit',
        'DiagnosticReport',
        'DocumentReference',
        'Immunization',
        'MedicationRequest',
        'Medication',
        'MedicationAdministration',
        'CareTeam',
        'CarePlan',
        'SupplyDelivery',
        'Provenance',
        'AllergyIntolerance',
        'Device',
        'ImagingStudy'
        ) THEN 'NOT_TRACKED'  -- resourceType has no FOUNDATION table yet
        WHEN r.RAW_ENTRY_COUNT = COALESCE(f.FOUNDATION_LOADED_COUNT, 0) THEN 'MATCHED'
        ELSE 'MISMATCH'
    END AS STATUS
FROM RAW_COUNTS r
LEFT JOIN FOUNDATION_COUNTS f
    ON r.TRACKING_ID = f.TRACKING_ID
   AND r.RESOURCE_TYPE = f.RESOURCE_TYPE;
